theme-next/hexo-theme-next

_config.yml

The description of the gitment config is not clear enough.
Fix the misleading description of gitment config.
**Details will explain in Review.**
```yml
...
```

Fix misleading description of gitment

---

_config.yml
layout/_third-party/comments/disqus.swig

Allow user to choice when the disqus comments will be loaded.
If the `theme.disqus.async` have been changed to `true`, the disqus will be loaded when the visitor scrolls the page to the bottom.
* Link to demo site with this changes: https://tsanie.us/2018/01/10/lazyload-disqus/
```yml
disqus:
async: true
```

Support to lazy load the disqus comments

---

layout/page.swig

I have an article in the **_drafts** that contains 2 tags: compression, pngquant.
But the tags page shows the number with all articles including the draft ones.
* Screens like this: 
This commit changes the variable from reading `site.tags.length` to `site.tags.filter(t => t.length).length`, to make sure the result number will be right. (Also changes the categories)
> But I'm not familiar with swig, so the single filter is splitted to 6 lines, so it looks like too verbose. 😒 

Fix an issue about the categories/tags count.

---

_config.yml
layout/_layout.swig
layout/_third-party/bookmark.swig

Bookmark is a plugin that allow the users save their reading position. (using `window.localStorage`)
The users could just click the bookmark icon (like 🔖) in left-top of the page to save the position.
And when they visit your blog in the next time, they can continue the last reading position by clicking the bookmark icon from the home page.
On the left-top of the page: ![image](https://user-images.githubusercontent.com/980449/35190954-a0cf7de4-fea9-11e7-92ac-613af3e42552.png) → mouse over → ![image](https://user-images.githubusercontent.com/980449/35190958-b755120e-fea9-11e7-8a7e-7be5ca97e8f9.png)
When you click it:
* In the post page: it will …

Bookmark feature

---

_config.yml
docs/MATH.md
docs/zh-Hans/MATH.md
layout/_third-party/math/index.swig

`per_page` default is `false` and will render math EVERY PAGE.
`per_page` default is `true` and will render math on demand.
That is it will only render those posts with `mathjax: true` by default
Related: https://github.com/theme-next/hexo-theme-next/pull/32#issuecomment-359286588
```yml
math:
enable: false
per_page: true
```

Make per_page default to true to make math lazyloaded

---

layout/_macro/sidebar.swig
layout/_partials/footer.swig

Port from https://github.com/wafer-li/hexo-theme-next-reloaded/commit/ec845557e0e34948ef18b72cb9216eb9c934b10e
Add external+nofollow for social and powered when seo on
The social links and the powered links don't have `rel="external nofollow"`
Add `rel="external nofollow"` to social links and powered links, when seo enable
```yml
No change to config
```

Add more seo things

---

layout/_macro/sidebar.swig

I found the issue is still exists in the sidebar, just fix it. Related: https://github.com/theme-next/hexo-theme-next/pull/42
* Link to demo site with this changes: https://tsanie.us/about/
N/A

Fix the exists categories/tags count issue in the sidebar.

---

source/css/_common/components/third-party/algolia-search.styl

- related: https://github.com/iissnan/hexo-theme-next/issues/1764
Since [the **Muse** layout](https://github.com/theme-next/hexo-theme-next/blob/master/source/css/_schemes/Muse/_menu.styl#L2) specify the `.site-nav` is an **absolute** position with a z-index: 1030 in the mobile layout, that will lead its child `.algolia-popup` would be covered by the `.algolia-pop-overlay` (which with a [z-index: 2080](https://github.com/theme-next/hexo-theme-next/blob/master/source/css/_common/components/third-party/algolia-search.styl#L7))
Issue Number(s): https://github.com/iissnan/hexo-theme-next/issues/1764
Set the `.algolia-pop-overlay` to be hidden in the mobile layout, because the …

Fix an issue about the algolia search overlay.

---

_config.yml
layout/_third-party/search/localsearch.swig

The local search plugin will escape some special chars to the safety one, like `<` to `&lt;`, and `&` to `&amp;`, etc. (it's no problem).
But when you start a searching using the internal plugin, it will search keywords from the escaped one, for example, you couldn't find the `<`, because it has been escaped to `&lt;`.
* Screens: 
or
Now it add a switch to the `_config.yml`, when you turning it on, the data will be unescaped before searching.
or
* Link to demo site with this changes: https://tsanie.us
```yml
local_search:
...
unescape: true
```

Add a switch to choice whether it will unescape the HTML strings for local searching

---

layout/_partials/head/head-unique.swig
layout/_partials/head/head.swig
source/js/src/post-details.js

Now we couldn't control the sidebar will be shown in some posts and not be shown in the other ones.
Issue Number(s): #92 
If you've written a front-matter `sidebar`, then the sidebar will be controlled by it.
* Link to demo site with this changes: https://tsanie.us/about/ (The sidebar will be shown even the page didn't have a TOC)
In any post source file `source/**/XXX.md`:
```md
...
date: 2018-01-28 21:16:00
sidebar: false
---
...
```

Support to set whether the sidebar will be shown in each single post.

---

docs/ALGOLIA-SEARCH.md
docs/zh-CN/ALGOLIA-SEARCH.md

According to issue [#68](https://github.com/theme-next/hexo-theme-next/issues/68), Add CN doc of Algolia search to install it successfully in NEXT V6+.

Add CN doc of Algolia search

---

_config.yml
docs/MATH.md
docs/zh-CN/MATH.md

Current we use the CDNJS as the default CDN, which is blocked in some parts of China.
Use the jsDelivr as default math cdn
jsDelivr has the ICP license issued by Chinese government, and has pretty access speed in China.
see https://github.com/theme-next/hexo-theme-next/pull/98#issuecomment-362014034
* Link to demo site with this changes: https://wafer.li
```yml
mathjax:
cdn: //cdn.jsdelivr.net/npm/mathjax@2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
katex:
cdn: //cdn.jsdelivr.net/npm/katex@0.7.1/dist/katex.min.css
```
I am not so sure.

Use jsdelivr as default cdn and update docs

---

_config.yml
layout/_partials/head/head.swig

The needmoreshare2 vendors not work.
See here:
https://github.com/theme-next/hexo-theme-next/blob/92061f90d90ca2aeece57c611c46bd6e2a08cbe9/layout/_third-party/needsharebutton.swig#L3-L5
And here:
https://github.com/theme-next/hexo-theme-next/blob/1cb4d086bd31c061764ceadddc82a729e4dc3fd5/layout/_partials/head/head.swig#L9-L11
It needs the `needmoreshare2_js` and `needmoreshare2_css`, but the `vendors` section only has `needMoreShare2`
https://github.com/theme-next/hexo-theme-next/blob/802b9a88c4e39107427069d2d3583db33f9d4d6b/_config.yml#L892-L894
Change the `needMoreShare2` to `needmoreshare2_js` and `needmoreshare2_css` to make it work.
* Link …

Fix needmoreshare2 vendors

---

_config.yml
layout/_third-party/bookmark.swig

There is no need to clone the bookmark repo into the `source/lib`, just set the CDN url instead.
* Link to demo site with this changes: https://tsanie.us (removed the `source/lib/bookmark` directory)
```yml
vendors:
...
bookmark: https://cdn.jsdelivr.net/gh/theme-next/theme-next-bookmark@1.0.0/bookmark.min.js
```

Let the bookmark support the CDN

---

_config.yml

User doesn't know reading_progress can use cdn.
Issue Number(s): #105 
User knows reading_progress can use cdn.
```yml
vendors:
reading_progress: #cdn url
```

add reading_progress to vendors

---

source/js/src/motion.js
source/js/src/utils.js

After upgrade to jQuery 3.3.1
https://api.jquery.com/size/
The .size() method was deprecated in jQuery 1.8 and removed in 3.0, use .length instead
The page renders correctly when upgrade to jQuery 3.3.1
* Link to demo site with this changes: https://raincal.com
```yml
...
```

Use .length instead of .size()

---

_config.yml
docs/ALGOLIA-SEARCH.md
docs/zh-CN/ALGOLIA-SEARCH.md
source/css/_common/components/third-party/algolia-search.styl

Add 3rd module installation instructions and CDN vendors support,
```yml
...
```

Update algolia search docs with vendors

---

layout/_macro/sidebar.swig

Remove `signature` option and stay only `description`  for exclude users confused when `seo: true`.

Keep `description` option only when `seo` enabled.

---

_config.yml
source/css/_schemes/Pisces/_layout.styl
source/css/_schemes/Pisces/_sidebar.styl
source/css/_variables/Gemini.styl

Related Issue Number(s): #67, https://github.com/iissnan/hexo-theme-next/issues/1980
Allow the users configure their sidebar width for Gemini Scheme manually.
* Link to demo site with this changes: https://tsanie.us (with a custom sidebar width: 300px)
```yml
sidebar_width: 300
```

Support to manual configure the sidebar width of the Gemini Scheme.

---

source/js/src/utils.js

* Link to demo site with this changes: https://raincal.com/2017/08/07/deploy-flarumChina-with-docker/
```yml
...
```

fix(fancybox): add data-fancybox attribute for fancybox3

---

_config.yml
languages/_en.yml
layout/_macro/post-related.swig
layout/_macro/post.swig
source/css/_common/components/third-party/related-posts.styl
source/css/_common/components/third-party/third-party.styl

Not an issue but according to the feature in roadmap.
By using the [hexo-related-popular-posts](https://github.com/tea3/hexo-related-popular-posts) that mentioned in the https://github.com/iissnan/hexo-theme-next/issues/1130
Issue Number(s): #67 
When the user have enable the feature, the related posts will be shown in the bottom of the post.
* Link to demo site with this changes: https://tsanie.us/2018/01/07/replace-destiny-child-character-next/
```yml
related_posts:
enable: true
title: # will be shown as the title
params:
maxCount: 5
#ulClass: 'popular-posts'
#PPMixingRate: 0.0
#isDate: false
#isImage: false
#isExcerpt: …
```

Feature: related posts, according to #67

---

source/css/_common/components/sidebar/sidebar-toc.styl

**Before:**
**After:**
***
Fix to Fix: https://github.com/iissnan/hexo-theme-next/commit/60711f9de5d9c10986f91b5c2922b9d7b894db34#diff-96b203dc237746cf97903c810f062203R36

Fix justify TOC items in sidebar.

---

_config.yml
layout/_third-party/comments/valine.swig

IE doesn't support the [Arrow Function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions), change it back to the anonymous function.
Issue Number(s): #138 
Valine comment will work right in the IE browser.
N/A

Fix a syntax issue about IE compatible

---

scripts/tags/include-raw.js

Usage:
`{% include_raw '_data/path/to/file.html' %}`
Path is relative to your site source directory.
***
For example, create `hexo/source/_data/templates/custom.html`  then add tag in post:
```
{% include_raw '_data/templates/custom.html' %}
```
All contents from `custom.html` will include into your post(s) in raw mode.

Added `include_raw` tag feature.

---

layout/_macro/post.swig
source/css/_schemes/Mist/_base.styl

- [x ] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x ] Tests for the changes have been added (for bug fixes / features).
- [x ] Muse | Mist have been tested.
- [ x] Pisces | Gemini have been tested.
The margins for h1-h6, <p> tags in theme Mist are different from those other themes. It's better to keep the consistency across themes.
Issue Number(s): #146
Margins in Mist theme are changed to be consistent with other themes.
```yml
...
```

Mist margin settings consistence and a small typo fixed

---

source/css/_common/scaffolding/base.styl

h1 margin missed
h1 margin added
```yml
...
```

fix missing margin for h1

---

source/css/_common/components/header/github-banner.styl
source/css/_mixins/base.styl

1. Added tablet-mobile mixin template for use < 991px.
2. Fixed GitHub banner color inverting for Pisces/Gemini schemes in tablet styles.
3. Fixed Github banner top alignment with `mobile_style_economy` option for Mist scheme.

Fixes for GitHub banner option.

---

.github/ISSUE_TEMPLATE.md

Fix Task List format in Markdown.

FIX ISSUE TEMPLATE

---

source/css/_common/components/post/post-expand.styl

Since the caption position is [lifted it up ( if present ) at least 20px](https://github.com/iissnan/hexo-theme-next/pull/1864). The caption is embedded in bottom of fig which may cause a lap over.
The margin bottom need to set 25px to preserving a space of 5px between the picture and the caption text. 
```yml
...
```

FIX FIG MARGIN

---

layout/_layout.swig
layout/_macro/menu/menu-badge-1.swig
layout/_macro/menu/menu-badge-2.swig
layout/_macro/menu/menu-item.swig
layout/_partials/header.swig
layout/_partials/sub-menu.swig
source/css/_schemes/Gemini/index.styl
source/css/_schemes/Mist/_menu.styl
source/css/_schemes/Pisces/_sub-menu.styl
source/css/_schemes/Pisces/index.styl
source/js/src/utils.js

1. Added dynamic sub-menu option in main `menu` option within hierarchy structure.
2. Added select class in menu items for all possible sub-menu's (utils.js).
3. Removed `float: right` menu style in Mist scheme for better sub-menu(s) alignment.
```yml
menu:
News: / || info-circle
Docs:
default: /docs/ || book
Getting Started: /getting-started/ || flag
Theme Settings: /theme-settings/ || star
Third Party Services:
default: /third-party-services/ || plug
Algolia Search: /algolia-search/ || adn
Tag Plugins: /tag-plugins/ || rocket
Advanced Settings: /advanced-settings/ || rocket
FAQ's: /faqs/ || life-ring
Platforms: /platforms/ || retweet
```
Feature adapted for all schemes and, of course, needed to improve. For first release it looks like this:
Please, confirm this feature to insure there …

Added sub-menu feature.

---

languages/_en.yml
layout/_partials/head/head.swig
layout/_partials/header.swig
layout/_partials/pagination.swig

Get 45 on accessibility on lighthouse.
[report](https://cdn.rawgit.com/maple3142/b528b381a868330dfd2962bf44514112/raw/09c3eca6d4c488bbfd7b116b817b659b935ea930/before.html)
Get 90 on accessibility on lighthouse.
[report](https://cdn.rawgit.com/maple3142/b528b381a868330dfd2962bf44514112/raw/09c3eca6d4c488bbfd7b116b817b659b935ea930/after.html)
* Link to demo site with this changes: [https://blog.maple3142.net/](https://blog.maple3142.net/)
Nothing.

Improve accessibility

---

_config.yml
layout/_third-party/analytics/lean-analytics.swig

Fix single quotes in lean-analytics.swig are not escaped

---

_config.yml
layout/_partials/head/head-unique.swig

There is `keywords` configuration both in `Hexo` and `Theme-Next`.
- Hexo generates keywords from `page.keywords`, `page.tags` and `config.keywords`. [source code](https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/open_graph.js#L41)
- Next generates keywords from `page.keywords`, `page.tags` and `theme.keywords`. [source code](https://github.com/theme-next/hexo-theme-next/blob/master/layout/_partials/head/head-unique.swig#L1)
Remove `keywords` configuration in  `Theme-Next`.
It works fine with one configuration.

Remove keywords in Theme-Next

---

docs/ALGOLIA-SEARCH.md
docs/zh-CN/ALGOLIA-SEARCH.md
source/css/_common/components/third-party/algolia-search.styl

In [former file](https://github.com/theme-next/hexo-theme-next/pull/119/files#diff-a8164b1286413219a3653b987a7ebcba), all svg-related element in blog would be blocked leading to the conflict between algolia and svgs.  [Related issue](https://github.com/theme-next/hexo-theme-next/issues/172).
```diff
+svg path {
+ display: none;
+}
```
In this PR, more exact element are found and blocked using algolia CDN , in this way, other svg-related element can be display usually. More related issues about the missing of SVG can be solved.

Fix svg confict in algolia vender

---

_config.yml
docs/LEANCLOUD-COUNTER-SECURITY.md
docs/zh-CN/LEANCLOUD-COUNTER-SECURITY.md

Add EN doc for leancloud counter security

---

languages/_en.yml
layout/_macro/post.swig

At present, there is a loss in comment text.
Facebook comments has added already ([example](https://www.lavicle.com/2017/06/10/hello-world/)). 
https://github.com/sli1989/hexo-theme-next/blob/e6d4dd5ad7f178708754e0bab01863f267c7a900/layout/_macro/post.swig#L139
Disqus auto return the `Comments`: [1 Comment example](https://wafer.li/Buying/Realforce%2087u/), [2 Comments ](https://wafer.li/Kotlin/Kotlin%20%E5%BC%82%E5%B8%B8/), [6 Comments ](https://wafer.li/Kotlin/Kotlin%20%E5%AF%B9%E8%B1%A1/)
Hypercomments ([example](https://almostover.ru/2017-04/advanced-ssl-tuning/)) & changyan ([example](http://www.zhaiqianfeng.com/2017/03/changyan-for-hexo-next-theme.html)) & valine & …

Add comment text

---

source/css/_common/components/post/post-meta.styl

The comment count in mobile doesn't display. It's a necessary meta, so display it without a enable option.
Issue Number(s): #180
Add the count meta in post.
before
after
* Link to demo site with this changes: http://test.saili.science/2018/03/17/hello-world/
```yml
...
```

Add comment count in mobile

---

layout/_macro/post.swig
layout/_partials/footer.swig

- Redundant space in 'post.symbols_time' are deleted.
- `&#58` are replaced with 'symbol.colon' in all file to keep pace with different lang.
```yml
...
```

Add symbol.colon in meta text

---

_config.yml
source/css/_common/components/highlight/highlight.styl

- Optimize the visual style of codeblock
- Add the option of border-radius of codeblock. if `codeblock.rounded=false`, the codeblock would be loaded with rounded corner.
`codeblock.rounded=true`
* Link to demo site with this changes: http://test.saili.science/posts/codeblock-test/
```yml
...
```

Update codeblock style and add border-radius settings

---

_config.yml
layout/_partials/footer.swig
source/css/_common/components/footer/footer.styl

Replace footer icon with beating heart, thanks @reuixiy
* Link to demo site with this changes: http://test.saili.science/posts/codeblock-test/
```yml
...
```

Refactor footer icon with animation

---

docs/LEANCLOUD-COUNTER-SECURITY.md
docs/zh-CN/LEANCLOUD-COUNTER-SECURITY.md

Fix image urls in docs/LEANCLOUD-COUNTER-SECURITY

---

source/js/src/utils.js

some uglyify tool will add "use strict" to the file, this fix will prevent error "i is not defined"

Fix bug in utils.js

---

_config.yml
layout/_partials/footer.swig
scripts/helpers.js

```diff
footer:
-  powered: true
```
```yml
footer:
powered:
enable: true
version: true
```

Added `footer.powered.version` option to display Hexo version in footer.

---

_config.yml
layout/_macro/post.swig

```yml
Without origin hexo and NexT _config.yml  
```  
In post time area, only display with date. like below
> Posted on 2018-04-10
```yml  
date_format: YYYY-MM-DD
time_format: HH:mm:ss
post_meta:
...
date_time_merge: true
...
```  
It can merge hexo config's date and time format together. like:
> Posted on 2018-04-10 19:44:03
* Link to demo site with this changes: [MyGithubPage](https://jackey8616.github.io)
```yml  
post_meta:
...
date_time_merge: true
...
```
and everything worked.

Add date_time_merge filed into post_meta

---

_config.yml
languages/en.yml
layout/_macro/post.swig
layout/_partials/footer.swig

1. Modified default settings: `AWL = 4`; `WPM = 275`.
2. Added suffix as string parameter if time to read less then 60 minutes. Default: `mins.`
3. Refactored language translates.
```js
$ npm test
Hexo Symbols Count Time
Test symbolsCount function & check should / expect / assert
✓ should - 22
✓ expect - 22
✓ assert - 22
Test symbolsCount < 999
✓ Symbols: 569 => 569
Test symbolsCount > 999
✓ Symbols: 1337 => 1.3k
Test symbolsCount > 9999
✓ Symbols: 10703 => 11k
Test symbolsCount & symbolsTime (awl / wpm)
✓ Symbols: (symbolsCount = 90)
✓ Time: [awl = 5, wpm = 200] => 1 mins.
✓ Time: [awl = 5, wpm = 5] => 4 mins.
✓ Time: [awl = 1, wpm = 50] => 2 mins.
Test symbolsTime (< 58 minutes / > 1:08)
✓ Time: 64218 = 58 => 58 minutes
✓ Time: 74921 = 68 => 1:08
```

Added support for hexo-symbols-count-time v0.4.0

---

_config.yml
languages/en.yml
languages/zh-TW.yml
layout/_layout.swig
layout/_third-party/copy-code.swig
layout/_third-party/copycode.swig

No copy button in codeblock.
Issue Number(s): #67 #222
A copy button on top-right of code block. 
* Link to demo site with this changes: https://blog.maple3142.net/
```yml
copycode: true
```

add copy codeblock button

---

layout/_third-party/copy-code.swig

Wrong button position after scrolling.
Button will be fixed relative to parent.
* Link to demo site with this changes: https://blog.maple3142.net/
```yml
...
```

fix css of copycode button

---

.jshintrc
_config.yml
bower.json
layout/_layout.swig
layout/_partials/footer.swig
layout/_partials/head/head.swig
layout/_scripts/boostrap.swig
layout/_scripts/commons.swig
layout/_scripts/pages/post-details.swig
layout/_scripts/schemes/gemini.swig
layout/_scripts/schemes/pisces.swig
layout/_third-party/exturl.swig
layout/_third-party/scroll-cookie.swig
layout/_third-party/search/algolia-search/assets.swig
package.json
scripts/helpers.js

1. Replaced Hexo version by full `env` variable. Here is values: https://github.com/hexojs/hexo/blob/373b9c745cb5dfe25e942e720aca2cdac78e1874/lib/hexo/index.js#L47-L55
2. From this moment version of NexT will be readed from `package.json` file. So, no need to set version in NexT `_config.yml` file anymore. Also, all other values from `package.json` can be readed with `next_env('value')` function in template.
3. Edited `package.json` and `bower.json` (correct author values, some tags).

Added Hexo and NexT environment variables.

---

source/css/_schemes/Mist/_posts-expanded.styl

With the default font size(14px), text font of the Mist scheme is smaller than other schemes on mobile phone, and is also smaller than release 5.1.3。
Issue Number(s): #245 #38 
changed font-size from $font-size-small to $font-size-base, 12px -> 14px

fixed text font of the Mist scheme is smaller than other schemes on mobile phone

---

_config.yml
layout/_macro/post.swig
layout/_macro/sidebar.swig
source/css/_common/components/sidebar/sidebar-author.styl

1. refactor the avatar option, add the enable option of rounded, opacity and rotated.
3. the feature is not working in mobile.
* Link to demo site with this changes:  http://test.saili.science/
```yml
avatar:
url: #/images/avatar.gif
rounded: false
opacity: 1
rotated: false
```

Add avatar round & opacity & animation feature

---

layout/_macro/post-copyright.swig

This theme does not support customized copyright contents.
Use can defined there copyright contents in post
In post, user can use `copyright` in front-matter block to define their own copyright contents

Allow customized copyright contents

---

_config.yml
layout/_macro/post.swig
layout/_third-party/analytics/lean-analytics.swig
layout/_third-party/comments/valine.swig

```yml
valine:
...
visitor: false # Article reading statistic https://valine.js.org/visitor.html
...
```

Update valine comment system version

---

languages/en.yml
layout/_macro/post.swig

Since its static blog, when the date goes on, the non-display date in post meta seems unusual.
Issue Number(s): https://github.com/theme-next/hexo-theme-next/pull/228#issuecomment-389430077
- Use `date(post.updated)` when `created_at=false` & `date(post.date) = date(post.updated)`
- ~~nominalize the `posted` (posted time), `edited` (modified time), `in` (post folder ) in post meta for unification and convenient translation.~~
* Link to demo site with this changes: https://test.saili.science/
```yml
...
```

Fix the post date display bug and Updated the post meta display

---

layout/_third-party/analytics/lean-analytics.swig

Refactor lean-analytics.swig to use REST API to avoid conflicts with valine

---

layout/_third-party/comments/livere.swig

When you use LiveRe comment box, LiveRe uses full URL as its identifier by default. Consider these 2 URLs:
```
example.com/my_article/
example.com/my_article/index.html
```
These two URLs actually  access to the same page, but LiveRe will treat them differently, so you won't see same comments on these two URLs.
I added `refer` to be equal to `page.path` according to the [official documentation](https://101.livere.co.kr/livere9com/pdf/guide/LiveRe_City_Chn.pdf). Since this way is also be used in disqus when defining identifier:
https://github.com/theme-next/hexo-theme-next/blob/79932de3431db6c7a2c306e980dc78e77af4dfb3/layout/_third-party/comments/disqus.swig#L11
I believe it can fix this bug.

add refer for livere

---

layout/_third-party/comments/disqus.swig

`document.documentElement.scrollTop` always return 0 in safari, so Disqus will never pop up. 
- Safari behaves as correct as Chrome.
- fetching `scrollTop` in realtime to avoid some error, e.g. images lazy-loading or manually resizing browser window.
---
p.s. PR from a back-end developer, not so familiar with front-end code. Feel free to give me some comments XD. Cheers.

Fix disqus lazyload not working in Safari

---

source/css/_common/scaffolding/mobile.styl
source/js/src/schemes/pisces.js
source/js/src/utils.js

1. If scrolled to bottom, sidebar cannot automatically set to top (#114).
2. If scrolled and `b2t` & `scrollpercent` enabled, back to top don't appear before user scrolled the page.
3. Fix for external links alignment with mobile style.

Fixes for sidebar in Pisces / Gemini schemes.

---

source/css/_common/components/highlight/highlight.styl
source/css/_common/components/post/post-title.styl
source/css/_common/components/post/post.styl
source/css/_common/scaffolding/base.styl
source/css/_common/scaffolding/tables.styl
source/css/_mixins/base.styl

Issue Number(s): fix #425 
1. break words doesn't work in PC.
2. Firefox doesn't support `word-break: break-word;`
https://caniuse.com/#search=word-break
```yml
...
```

fix: Break words on PC and Firefox

---

source/css/_common/components/back-to-top-sidebar.styl
source/css/_schemes/Gemini/index.styl

1. Fixed wrong margin for b2t in sidebar.
2. Replaced `sboffset` with `$sidebar-offset` for Gemini.

Fixes for b2t & variables refactoring.

---

_config.yml
docs/MATH.md
docs/zh-CN/MATH.md

The bootCSS CDN are redirect to cloudflare CDN.
It return 301 Moved Permanently.
This redirect brought on block mathjax font when chrome and firefox. It's CORS policy of browser. Actually two issues are reported hexo repostitory.
* [mathjax bug on chrome and firefox](https://github.com/hexojs/hexo/issues/3279)
* [Hexo Math formula could not display in the right way](https://github.com/hexojs/hexo/issues/3280)
Delete bootCSS CDN settings.

Delete Bootcss settings and docs

---

_config.yml
layout/_third-party/analytics/growingio.swig
layout/_third-party/analytics/index.swig

~~Issue Number(s): N/A~~
Add a analytics service just as `Baidu Analytics` or `Google Analytics`
~~* Screens with this changes: N/A~~
~~* Link to demo site with this changes: N/A~~
```yml
growingio: [your growingio ID]
```

Add growingio analytics

---

source/js/src/utils.js

```
[![](/images/icon.gif)](https://github.com)
```
When you click the image, fancybox will load, then report an error because `https://github.com` is not an image.
Issue Number(s):  #399 and #394 
Prevent the img in an anchor from being wrapped as fancybox.
When you click the image, `https://github.com` will open in a new tab.
```yml
...
```

Fix #399 and #394

---

layout/_third-party/math/mathjax.swig

If a formula rendered by Mathjax is beyond the width of the screen, the default behavior will result in a horizontal scrollbar, which is very unattractive.
Issue Number(s): #460 
This pr display Mathjax within overflow.
* Link to demo site with this changes: https://test.saili.science/posts/math-test/
```yml
...
```

Fix mathjax overflow

---

source/css/_common/components/highlight/highlight.styl

Lisp languages (like Scheme) don't highlight well.
Lisp languages should look better. Their builtin names will display in orange color, just as highlight.js does.
❌
See https://github.com/highlightjs/highlight.js/commit/8616294df138a2895cd71fcb9a1483a1ce00b143

Define "builtin-name" for Lisp languages

---

source/css/_common/components/highlight/highlight.styl

Improve highlighting for Lisps

---

layout/_macro/post-collapse.swig
layout/_macro/post.swig

Issue Number(s): #495, #473 and #231
Hexo generates wrong post link when website is in a subdirectory,
because `url_for()` executed twice on `post.link`
```yml
...
```

Fix #495, #473 and #231

---

layout/_partials/breadcrumb.swig
layout/_partials/header/sub-menu.swig

When submenu path name is same, submenu2 is rendered twice

fix submenu when path name is same

---

layout/_third-party/comments/disqus.swig

Issue number: #494
Before:
After:

Fixed Disqus bug if in permalink exists symbol «'» .

---

_config.yml
layout/_partials/header/brand.swig
source/css/_common/components/header/site-meta.styl
source/css/_schemes/Muse/_logo.styl
source/css/_schemes/Pisces/_brand.styl
source/js/src/motion.js
source/js/src/utils.js

Issue Number(s): #274
Custom logo for Gemini & Pisces
```yml
custom_logo:
enabled: true
image: /path/to/your/logo.jpg
```

Reorganize #274 Custom logo for Gemini & Pisces

---

source/css/_common/scaffolding/base.styl
source/css/_schemes/Gemini/index.styl

Any inline code within headers will have mismatched font-size. The inline code will have the same font-size as fenced code, whereas it should have adjusted to whatever font-size the header has.
The inline code should have adjusted to whatever font-size the header has.
* Screens with this changes: above
* Link to demo site with this changes: https://bolunzhang.me/2018/12/14/static-versus-dynamic-libraries/
N/A

Fix inline code font-size mismatch within headers

---

_config.yml
source/css/_common/components/pages/archive.styl
source/css/_common/components/post/post-reward.styl

Fix #531, format code in _config.yml

---

_config.yml
layout/_macro/sidebar.swig

Don't support set toc max_depth
Issue Number(s):  #527
Add toc max_depth support
* <https://jiangtj.gitlab.io/next-test/muse/2018/12/22/max_depth_in_config/>
* Config set max_depth: 2
* <https://jiangtj.gitlab.io/next-test/muse/2018/12/22/max_depth_in_post/>
* This post set toc_max_depth:1
```yml
toc:
max_depth: 6
```
Or in post:
```
toc_max_depth: 6
```

Add toc max_depth support

---

_config.yml
layout/_third-party/math/mathjax.swig

Issue Number(s): #553 
Removed  invalid CDN due to https://www.mathjax.org/cdn-shutting-down/
```yml
...
```

Fix #553 New Feature: mhchem support

---

docs/LEANCLOUD-COUNTER-SECURITY.md
docs/zh-CN/LEANCLOUD-COUNTER-SECURITY.md

…ests pass
PV does not increase according to the older class function.
Make PV increase and let concurrent requests pass.
```yml
...
```

bugfix: make request time of leancloud saved and let concurrent requests pass

---

source/css/_common/scaffolding/tables.styl
source/js/src/utils.js

fix(markdown): make table scrollable

---

layout/_partials/post/wechat-subscriber.swig
layout/_partials/search/index.swig
layout/_third-party/analytics/lean-analytics.swig
layout/_third-party/baidu-push.swig
scripts/filters/exturl.js
scripts/helpers/next-url.js

Issue resolved #594
```yml
...
```

Fix #594: External links didn't get replaced in index page

---

_config.yml
layout/_macro/sidebar.swig
source/css/_common/components/sidebar/sidebar-dimmer.styl
source/css/_common/components/sidebar/sidebar.styl

Issue resolved #606
```yml
...
```

Feature: Close sidebar when click any blank part (#606)

---

_config.yml
layout/_layout.swig
layout/_third-party/quicklink.swig

When a page has finished loading, quicklink will attempt to use fetch() or falls back to XHR to prefetch URLs (same origin and ignore # such as #more) for links that are in-viewport during idle time.
Put simply, the links you can see will be prefetched. For example, if your sidebar is hidden at first, you need to open the sidebar to prefetch the rss link because you can't see it.
* [1v9's Blog](https://1v9.im)
```yml
...
quicklink: true
...
vendors:
...
quicklink: //cdn.jsdelivr.net/npm/quicklink@1.0.0/dist/quicklink.umd.js
...
```

Feat: Add quicklink support

---

_config.yml
layout/_macro/sidebar.swig
layout/_partials/post/post-copyright.swig

By default, the link of CC license is like this: [https://creativecommons.org/licenses/by-nc-nd/4.0/](https://creativecommons.org/licenses/by-nc-nd/4.0/)
If add deed.zh to language option in creative_commons the the link will be [https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh](https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh)
* See https://1v9.im
* Add a value to language
```yml
creative_commons:
license: by-nc-sa
sidebar: true
post: true
language: deed.fr
```
* Or leave it empty, nothing happend.
```yml
creative_commons:
license: by-nc-sa
sidebar: true
post: true
language:
```

Feat: Add language option to creative_commons

---

_config.yml
layout/_third-party/quicklink.swig

Remove hardcode in quicklink.swig, now timeout, priority, ignores can be set up in _config.yml,
> My server is in Seattle, it seems too bad, please ignore the network delay, which has nothing to do with quicklink.
* [1v9's Blog](https://1v9.im)
```yml
...
quicklink:
enable: true
timeout: 3000
priority: true
ignores:
...
```

Refactor: Add some options for quicklink

---

_config.yml
layout/_third-party/copy-code.swig

Only one style available for copy button.
Will be able to use another style of button: `flat`
Multi-line:
Single-line:
```yml
codeblock:
border_radius:
copy_button:
enable: true
show_result: true
style: flat
```

Feat: Add another copy button variant

---

layout/_third-party/copy-code.swig

Refactor it with how clipboard.js works under the hood
When you copy something like this:
In chromium-based browsers, it will result in: (There's a linefeed on the start.)
The linefeed on the start will no longer exist, and it compatibility should be as good as https://clipboardjs.com/#browser-support
* Link to demo site with this changes: https://blog.maple3142.net/
No

Refactor: copy code

---

_config.yml
layout/_third-party/quicklink/index.swig

#637 introduced `per_page: true` option to load quicklink on demand, but home page and archive page can't be fully controlled.
* Now quicklink will load on demand by default.
* add `quicklink: true` in front matter for those pages or posts you want.
* Home page and archive page can be controlled through `home: ` and `archive: ` option.
```diff
quicklink:
enable: true 
- per_page: true
+ home: true # enable or disable quicklink on home page
+ archive: true # enable or disable quicklink on archive page
```

Refactor: Improve usage of quicklink

---

_config.yml
layout/page.swig

Font color or size of tagcloud can't be customized.
```yml
tagcloud:
enable: true
min: 50
max: 100
start: green
end: '#5c50e6'
```

Feat: Custom font size and color of tagcloud

---

_config.yml
layout/_third-party/comments/gitalk.swig

Issue resolved: #651
* Language can be foced.
* leave language empty, same as before
* Add es-ES
```yml
gitalk:
enable: false
github_id:  # Github repo owner
repo:  # Repository name to store issues
client_id:  # Github Application Client ID
client_secret:  # Github Application Client Secret
admin_user:  # GitHub repo owner and collaborators, only these guys can initialize github issues
distraction_free_mode: true # Facebook-like distraction free mode
+ language:
```

Feat: Add force language to Gitalk

---

_config.yml
layout/_layout.swig
layout/_third-party/copy-code.swig
layout/_third-party/quicklink.swig
layout/_third-party/quicklink/quicklink.swig
scripts/tags/exturl.js
scripts/tags/group-pictures.js
scripts/tags/video.js
source/css/_common/components/header/header.styl
source/css/_common/components/highlight/highlight.styl
source/css/_common/components/tags/tags.styl
source/css/_common/scaffolding/base.styl
source/css/_schemes/Pisces/_sidebar.styl

Add warnings to `exturl` tag & Add `video` tag & Code style update

---

_config.yml
layout/_third-party/pdf.swig
scripts/tags/pdf.js

Refactoring pdf.js

---

source/css/_common/components/highlight/diff.styl

```diff
+ green background for added line
- red for deleted line
but old css style use wrong colors
```
for diff code block, currently it make wrong background color for added/deleted line for some hight theme.
Issue resolved: yes
exchange the color variable value and problem sovled.
just a small change for css style

 fix diff code hightlight problem

---

layout/_third-party/analytics/google-analytics.swig

google tag will load like this `//www.googletagmanager.com/gtag/js?id=[object%20Object]`
`//www.googletagmanager.com/gtag/js?id=UA-XXXXXXX-XXX`
Change `google-analytics.swig` from
``` swig
<script async src="//www.googletagmanager.com/gtag/js?id={{ theme.google_analytics }}"></script>
```
to
``` swig
<script async src="//www.googletagmanager.com/gtag/js?id={{ theme.google_analytics.tracking_id }}"></script>
```

Fix lost tracking_id in google_analytics

---

_config.yml
layout/_macro/post.swig
layout/_partials/share/likely.swig
source/css/_common/components/post/post.styl

Issue resolved: #491
```yml
likely:
enable: true
look: big
networks:
twitter: Tweet
facebook: Share
linkedin: Link
gplus: Plus
vkontakte: Share
odnoklassniki: Class
telegram: Send
whatsapp: Send
pinterest: Pin
```

Feat: Add likely share support

---

layout/_third-party/math/mathjax.swig

The detail is discussed under issue #645 , maybe this PR can make some help. Please refer to the last two paragraph of [my blog](https://i-m.dev/posts/pnuetp.html)(only in Chinese) for its change explanation.

Fix for issue #645 (and also #658)

---

_config.yml
layout/_layout.swig
layout/_macro/sidebar.swig
layout/_third-party/chatra.swig
layout/_third-party/tidio.swig
source/css/_common/components/sidebar/sidebar-chat.styl
source/css/_common/components/sidebar/sidebar.styl
source/css/_schemes/Pisces/_sidebar.styl

Issue resolved: #577
- enable all chat services
- Mist, enable chatra sidebar button
- Pisces, enable tidio sidebar button
- sidebar button
```yml
chat:
enable: true
#service: chatra
service: tidio
text: Chat # button text, change it as you wish
```
- chat service
```yml
chatra:
enable: true
async: true
id: <ChatraID> # visit Dashboard to get your ChatraID
#embed: # unfinished experimental feature for developers, See: https://chatra.io/help/api/#injectto
tidio:
enable: true
key: <public key> # Public Key, See: https://www.tidiochat.com/panel/settings/developer
```

Feat: Add chatra and tidio support

---

source/css/_common/components/tags/note-modern.styl
source/css/_common/components/tags/note.styl

Issue resolved: #578
```yml
...
```

Fix #578: Link color in modern notes with `exturl`

---

_config.yml
layout/_macro/sidebar.swig

the icon of chat button in sidebar is hardcode -> fa-comment
use any icon in fontawesome v4
```yml
chat:
enable: true
service: chatra
#service: tidio
+icon: comment # icon in Font Awesome4, set false to disable icon
text: Chat # button text, change it as you wish
```

add icon option for chat button

---

source/css/_common/components/post/post-reward.styl

[![1.gif](https://i.loli.net/2019/03/16/5c8c700f4182e.gif)](https://i.loli.net/2019/03/16/5c8c700f4182e.gif)
```yml
...
```

Fixed `reward` button vertical align text

---

_config.yml
layout/_macro/post.swig
layout/_partials/post/reward.swig
source/css/_common/components/post/post-reward.styl
source/css/_common/components/post/post.styl

Issue resolved: https://github.com/theme-next/hexo-theme-next/issues/596, https://github.com/iissnan/hexo-theme-next/pull/2199
```yml
...
```

Refactoring post reward

---

source/css/_common/components/back-to-top-sidebar.styl
source/css/_common/components/back-to-top.styl
source/css/_common/components/post/post.styl
source/css/_common/components/sidebar/sidebar-author-links.styl
source/css/_common/components/sidebar/sidebar-blogroll.styl
source/css/_common/components/sidebar/sidebar-toggle.styl
source/css/_common/components/sidebar/sidebar.styl
source/css/_mixins/Pisces.styl
source/css/_schemes/Pisces/_sidebar.styl
source/js/src/post-details.js

Issue resolved: #482
Fixed 3 bugs:
- #482, make back2top display on mobile 
- Add spaces between sidebar elements
- Add `border-bottom-color` settings of `exturl` in sidebar
```yml
...
```

Bugfix: `back2top` button on mobile, sidebar item margin and sidebar `exturl` link color

---

source/css/_common/components/sidebar/site-state.styl

Make `site-state-item` centered using `flex`

---

_config.yml
layout/_partials/comments.swig
layout/_third-party/comments/disqusjs.swig
layout/_third-party/comments/index.swig

Issue resolved: #586
```yml
disqusjs:
enable: true
api:
apikey: <apikey> # register new application from https://disqus.com/api/applications/
shortname: <shortname> # See: https://disqus.com/admin/settings/general/
```

Feat: Add DisqusJS support

---

source/css/_common/components/header/github-banner.styl
source/css/_common/components/pages/schedule.styl
source/css/_common/components/post/post-expand.styl
source/css/_common/components/sidebar/sidebar-button.styl
source/css/_common/components/sidebar/sidebar-toggle.styl
source/css/_mixins/base.styl

Issue resolved: #722
```yml
...
```

Remove redundant styles

---

source/css/_schemes/Pisces/_sidebar.styl

Issue resolved: #734
```yml
...
```

Fix #734: Sidebar button style on Pisces and Gemini

---

_config.yml
layout/_partials/head/head-unique.swig
scripts/tags/button.js
scripts/tags/exturl.js
scripts/tags/full-image.js
scripts/tags/group-pictures.js
scripts/tags/label.js
scripts/tags/mermaid.js
scripts/tags/note.js
scripts/tags/pdf.js
scripts/tags/tabs.js
scripts/tags/video.js

Pages must placed in subdirectories with `index.html` names, e.g. `source/docs/troubleshooting/index.md` for pretty path with `canonical` option enabled:
But if we want to use pages in root directories and named as is with `*.html` suffix, `source/docs/advanced-settings.md`, canonical path will contain `*.html` suffix:
From now all links will be not only without `index.html`, but without `.html` too for pretty path with `canonical` option enabled. **And not need to set `permalink` in each page for that**.
Pages now can placed in root directories and named as is with `*.html` suffix, e.g. `source/docs/advanced-settings.md`:
- Link to demo site with this changes: …

Improved canonical path for vision in Google.

---

source/css/_common/components/third-party/math.styl
source/css/_common/components/third-party/third-party.styl

Issue resolved: #721, #736
```yml
...
```

Fix Mathjax style issue

---

source/css/_common/components/tags/label.styl

Removed `no-wrap` style from label tag

---

layout/_partials/page/breadcrumb.swig

Breadcrumbs now work with both `*.html` and `index.html` pages

---

.github/mergeable.yml

Bot used regular expressions and have a lot of settings. It's really powerful bot. More information [here](https://github.com/jusx/mergeable).
For now configuration setted up only on pull requests. Settings are given below.
Can be defined in similar way as in WIP Bot:
- WIP Your Title
- WiP Your Title
- [wip] Your Title
- WiP
- Work in progress (this label will be added)
Project name which will include any of below words (regex, case-insensitive):
- feat
- imp
- fix
- doc
- chore
So, our project with «Feats. / Imprs. / Fixes» name will accepted by bot configuration.
Just can't be empty, but may be defined with regex too.
***
**So, WIP Bot will be removed in accordance with this PR**.

Install Mergeable bot which totally replaced WIP bot and have more settings

---

source/css/_common/scaffolding/mobile.styl

List items appeared correctly in mobile with `mobile_layout_economy` option

---

source/css/_common/scaffolding/mobile.styl

```yml
scheme: Mist
mobile_layout_economy: true
```

Fix alignments for several elements with `mobile_layout_economy` option

---

layout/_third-party/analytics/google-analytics.swig

No "https" will result in an error。
```yml
...
```

Force HTTPS of `google-analytics.swig`. Again.

---

layout/_third-party/copy-code.swig

If we select something then click the copy button, code is copied but the previous selection will be gone.
The previous selection will be restored.
- Screenshots with this changes: 
- Link to demo site with this changes:
https://1v9.im/post/add-today-poetry-for-theme-next.html
```yml
codeblock:
copy_button:
enable: true
```

Restore the previous selection for `copy_button`

---

layout/_third-party/comments/disqus.swig
layout/_third-party/comments/disqusjs.swig

The whole web page is blocked and shows nothing until loading `embed.js` for Disqus is completed. Things get worse when some users (especially those Chinese users) have trouble connecting Disqus since they will see a blank page for a long time until the requested timeout.
In addition, for those who enable `pace.js`, they will see the progress bar circling for a long time until timeout.
The main cause of this problem is that loading `*.js` for Disqus blocks the rendering of the whole web page, so I simply defer the js loading until the whole page loading is completed.
https://github.com/theme-next/hexo-theme-next/blob/54a04c6209b60b554a47f19523553b0dda3c5336/layout/_third-party/c …

Improve page rendering by deferring disqus loading

---

.gitignore

> I don't know which type should be chose to describe this change, and it didn't need test.
The origin version was `!source/lib/font-awesome/*`, but it doesn't work. While I published my blog through Travis CI, It didn't include the font-awersome lib. And my Git GUI told that the dir was excluded by .gitignore.
Issue resolved: #413
Now it works.

Force include source/lib/font-awesome/

---

layout/_third-party/analytics/lean-analytics.swig

Use an regex to test if current `URL` includes `http://localhost` or `http://127.0.0.1` or `http://0.0.0.0` , if `true` then `return`.
If `return`, the number of visitors won't show in post and everything else is the same as before.
Issue resolved: #915

Ignore leancloud visitor from localhost

---

layout/_third-party/comments/valine.swig

Issue resolved: #922
With the Fix of unreachable issue with LeanCloud service in Valine, [the new Valine](https://valine.js.org/changelog.html#v1-3-7-2019-06-21) will automatically introduce `av-min.js`. 
So delete the section of `av-min.js` in Valine
```yml
...
```

Update LeanCloud issue in Valine

---

_config.yml

https://github.com/theme-next/hexo-theme-next/blob/7eaf354aba8a4859e596ca9da230b894f0d61980/_config.yml#L1161-L1166
_Originally posted by @stevenjoezhang in https://github.com/theme-next/hexo-theme-next/pull/926#issuecomment-505011399_

Remove unneeded leancloud-storage in `theme.vendors`

---

source/css/_common/components/highlight/highlight.styl
source/css/_common/components/post/post-expand.styl

```yml
...
```
Test code:
```
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus facilis quae quo architecto incidunt fugiat sapiente, assumenda labore, voluptate consequatur, nam cumque repellat hic vero odit. Quibusdam ipsa dicta at.
```
```yaml
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus facilis quae quo architecto incidunt fugiat sapiente, assumenda labore, voluptate consequatur, nam cumque repellat hic vero odit. Quibusdam ipsa dicta at.
```
{% codeblock yaml config.yml %}
Lorem ipsum dolor sit amet, consectetur …

Prune CSS about code highlight

---

scripts/tags/group-pictures.js

picture not loading properly
picture loaded correctly
none

Fix image line number calculation error, the picture can not be fully loaded

---

source/css/_common/components/tags/group-pictures.styl

Related issues: #713 #929.
Current layouts of GP in page and post are different and wrong.

Fix Group Pictures layout

---

_config.yml
layout/_layout.swig
layout/_scripts/three.swig
layout/_scripts/vendors.swig
layout/_third-party/three.swig

Allow delayed loading of three.js

---

layout/_macro/menu/menu-badge.swig
layout/_macro/sidebar.swig
layout/page.swig
scripts/merge-configs.js

Reverts theme-next/hexo-theme-next#954
In `generateBefore`, we can't get the count....
In `template_locals`, loop much times...
Revert this submit, the best way is not use _draft, and then don't calculate them, if you have many tags or categories

Revert "Avoid recalculating the number of tags and categories"

---

_config.yml
layout/_layout.swig
layout/_third-party/caniuse.swig
scripts/tags/caniuse.js

**Test for reviewers**
```bash
git pull origin pull/984/head
```
---
**Usage**
**`{% caniuse feature @ periods %}`**
---
**Examples**
```
{% caniuse %}
{% caniuse fetch %}
{% caniuse sharedarraybuffer @ current %}
{% caniuse loading-lazy-attr @ future_3,future_2,future_1 %}
{% caniuse link-rel-modulepreload @ past_1,past_2,past_3,past_4,past_5 %}
```
---
**Preview**
---
**Docs**
**`Not created.`**

Add new tag caniuse

---

_config.yml
layout/_partials/head/head.swig
layout/_scripts/vendors.swig
source/js/next-boot.js

```diff
-fastclick: false
vendors:
-  fastclick:
```
According to the docs of fastclick:
> Note: As of late 2015 most mobile browsers - notably Chrome and Safari - no longer have a 300ms touch delay, so fastclick offers no benefit on newer browsers, and risks introducing bugs into your application. Consider carefully whether you really need to use it.
And:
https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away
https://juejin.im/post/5cdf84e3f265da1bb564c79a

Remove fastclick support

---

_config.yml

Create `page settings` part in `_config.yml`

---

layout/_third-party/math/mathjax.swig

Issue resolved: #889
```yml
...
```

Fix list rendering problem when the list item contains mathjax formulae

---

_config.yml
scripts/merge-configs.js

Console reminder if new version released

---

layout/_partials/head/external-fonts.swig

When we set external font family of site title, no change happens.
``` yaml
font:
enable: true
title:
external: true
family: Caveat
size:
```
We can set external font family for site title.
```yml
font:
enable: true
title:
external: true
family: Caveat
size:
```

Fix site title's external font family bug

---

layout/_partials/head/external-fonts.swig

When `theme.font` has empty family value, the font list will contain empty value, thus resulting in the final string format being incorrect, and there are several situations.
Users could live font family value empty.

Fix a bug when `theme.font` has empty family value

---

source/js/schemes/pisces.js

Revert https://github.com/iissnan/hexo-theme-next/commit/12808375bed33801ef597640b2280711529bd1f2
```yml
...
```

Fix affix bug

---

source/css/_common/components/highlight/diff.styl

Fix codeblock diff highlight bug

---

layout/_layout.swig
layout/_partials/header/index.swig
layout/_partials/header/menu.swig
layout/_scripts/index.swig

Need more cache 2

---

scripts/tags/full-image.js
source/css/_common/components/tags/full-image.styl
source/css/_common/components/tags/tags.styl

Remove full-image tag

---

_config.yml
layout/_third-party/comments/changyan.swig
layout/_third-party/comments/disqus.swig
layout/_third-party/comments/disqusjs.swig
layout/_third-party/comments/gitalk.swig
layout/_third-party/math/mathjax.swig
layout/_third-party/tags/mermaid.swig
layout/_third-party/tags/pdf.swig
scripts/helpers/engine.js
source/js/utils.js

Fix issues caused by PJAX

---

_config.yml
layout/_macro/post.swig
layout/_partials/footer.swig
layout/_third-party/analytics/firestore.swig
layout/_third-party/analytics/lean-analytics.swig
scripts/filters/comment/common.js
source/css/_common/components/post/post-meta.styl
source/css/_common/components/post/post-title.styl

```diff
firestore:
-  bluebird: false
```
```yml
...
```

Improve the style of firebase analytics and post-meta

---

scripts/events/lib/config.js

Fix for strange bug if `next` directory will be placed under symlink in `theme` → Error: Cannot find module 'lodash/merge'. Releated to #1043.
1. Open `hexo/themes`
2. Move `next` physical directory somewhere else, for example `/home/username`
3. Create symlink in `themes` dir: `ln -s /home/username/next hexo/themes/next-symlink`
And get something like that:

Strange bug with symlinked `next` dir

---

source/css/_common/components/highlight/copy-code.styl
source/css/_common/components/highlight/highlight.styl
source/css/_common/components/post/post-title.styl
source/css/_common/components/sidebar/sidebar-button.styl
source/css/_mixins/base.styl
source/css/_schemes/Pisces/_sidebar.styl
source/js/utils.js

Fix several bugs reported in v7.3

---

_config.yml
layout/_partials/head/head.swig
layout/_partials/share/likely.swig
layout/_partials/share/needsharebutton.swig
layout/_scripts/three.swig
layout/_scripts/vendors.swig
layout/_third-party/bookmark.swig
layout/_third-party/comments/disqusjs.swig
layout/_third-party/comments/gitalk.swig
layout/_third-party/comments/valine.swig
layout/_third-party/math/index.swig
layout/_third-party/math/katex.swig
layout/_third-party/math/mathjax.swig
layout/_third-party/quicklink.swig
layout/_third-party/search/algolia-search.swig
layout/_third-party/tags/mermaid.swig
layout/_third-party/tags/pdf.swig

```diff
math:
-  engine: mathjax
-  #engine: katex
mathjax:
-    cdn: //cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
-    #cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML
+    enable: false
-    #mhchem: //cdn.jsdelivr.net/npm/mathjax-mhchem@3
-    #mhchem: //cdnjs.cloudflare.com/ajax/libs/mathjax-mhchem/3.3.0
+    mhchem: false
katex:
-    cdn: //cdn.jsdelivr.net/npm/katex@0/dist/katex.min.css
-    #cdn: //cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css
+    enable: false
-    copy_tex:
-      enable: false
-      copy_tex_js: //cdn.jsdelivr.net/npm/katex@0/dist/contrib/copy-tex.min.js
-      copy_tex_css: //cdn.jsdelivr.net/npm/katex@0/dist/contrib/copy-tex.min.css
+    copy_tex: false
pdf:
-  pdfobject:
-    cdn: …
```

Refactor vendors

---

layout/_third-party/analytics/lean-analytics.swig

Bug from this commit: https://github.com/theme-next/hexo-theme-next/commit/cbf604141424c9a036e249909c5b29bc014a941b#diff-d4f96cf2cea92b9d7c8d95bb034e2eb2R13 
In post page, cleancloud counter api returns all data then use the first item `var counter = results[0];`
In post page, cleancloud counter api returns current url correctly.

Fix leancloud counter bug

---

layout/_scripts/commons.swig
layout/_scripts/next-boot.swig
layout/_scripts/pages/post-details.swig
layout/_scripts/schemes/muse.swig
layout/_scripts/schemes/pisces.swig
layout/_third-party/search/algolia-search.swig
layout/_third-party/search/localsearch.swig
scripts/helpers/next-js.js

Add next_js helper

---

_config.yml
layout/_layout.swig
layout/_macro/post.swig
layout/_scripts/vendors.swig
source/css/_common/components/components.styl
source/css/_common/components/post/post.styl
source/css/_common/components/reading-progress.styl
source/js/local-search.js
source/js/next-boot.js
source/js/utils.js

Refactor reading-progress

---

_config.yml
layout/_partials/footer.swig

No feature of the public security record.
For Chinese users, except for the ICP record, they need public security record, too. I added this feature in this pull request.
- Screenshots with this changes: 
- Link to demo site with this changes: [https://www.matalking.com/](https://www.matalking.com/)
```yml
footer:
beian:
enable: true
icp: 京ICP备19031359号-2
gongan_id: 11010502038639
gongan_num: 京公网安备 11010502038639号
gongan_icon_url: /uploads/beian.png
```

Expand beian options for users in mainland China

---

_config.yml
scripts/events/lib/injects.js
scripts/filters/comment/changyan.js
scripts/filters/comment/default-config.js
scripts/filters/comment/disqus.js
scripts/filters/comment/disqusjs.js
scripts/filters/comment/facebook-comments-plugin.js
scripts/filters/comment/gitalk.js
scripts/filters/comment/livere.js
scripts/filters/comment/valine.js
scripts/filters/comment/vkontakte.js

Order of theme_inject is only determined by the priority of the injection.
Order of theme_inject is determined by the priority of the injection or special configuration in inject api.
Redesigned the sequential configuration of the multi-comment system.
```diff
comments:
style: tabs
active:
storage: true
nav:
-    #disqus: disqus
-    #facebook_comments_plugin: <i class="fa fa-facebook-official" aria-hidden="true"></i> facebook
-    #gitalk: Load Gitalk
+    #disqus:
+    #  text: Load Disqus
+    #  order: -1
+    #facebook_comments_plugin:
+    #  text: <i class="fa fa-facebook-official" aria-hidden="true"></i> facebook
+    #gitalk:
+    #  order: -2
```

Add order for theme_inject

---

layout/_macro/post.swig
layout/_partials/analytics/busuanzi-counter.swig

For `busuanzi` counter, if the script is not correctly loaded and executed, the display would be broken. Example:
```
阅读次数:   // here is supposed to be the page_pv counter value.
```
For `busuanzi` counter, if the script is not correctly loaded and executed, the container `span` will remain hidden, rather than broken display.
Automatically enable, if `busuanzi` is enabled.

Add container for busuanzi counter widget

---

source/js/next-boot.js
source/js/utils.js

If I use hexo [tag plugins](https://hexo.io/docs/tag-plugins.html#Include-Assets) to insert an image, it will not be rendered as medium zoom style.
i.e. `{% asset_img 2222.jpg  %}`
Medium zoom take effects on images whether imported with hexo `asset_img` tag or markdown-style `![](image.jpg)`.
Just set true.
```yml
mediumzoom: true
```

Fix fancybox & medium-zoom for hexo asset_img tag

---

_config.yml
source/css/_common/components/highlight/theme.styl

```yml
codeblock:
highlight_theme: solarized dark
copy_button:
enable: true
show_result: true
style: flat
```

New highlight themes

---

layout/_partials/sidebar/site-overview.swig
layout/_scripts/vendors.swig
source/css/_common/components/post/post-collapse.styl
source/js/motion.js
source/js/schemes/muse.js

Issues resolved: #1144, #1169, #1184

Fix Velocity motion issues

---

_config.yml
layout/_third-party/comments/valine.swig

```yml
valine:
recordIP: true # Whether to record the commenter IP
serverURLs: https://api.your_domian.com # When the custom domain name is enabled, fill it in here (itwill be detected automatically by default, no need to fill in)
```

New Valine options

---

_config.yml
layout/_third-party/analytics/google-analytics-pageview.swig
layout/_third-party/analytics/index.swig

Add an much lighter alternative to normal Google Analytics, as it requires no external script.
```yml
google_analytics_pageview:
tracking_id: # <app_id>
```
Find `google_analytics_pageview.tracking_id` and fill it.

Add Google Analytics Pageview

---

layout/_layout.swig
layout/_partials/footer.swig
layout/_partials/post/post-reward.swig
layout/_scripts/pages/schedule.swig
layout/page.swig
source/css/_common/components/pages/schedule.styl
source/css/_common/components/post/post-copyright.styl
source/css/_common/components/post/post-gallery.styl
source/css/_common/components/post/post-reward.styl
source/css/_common/components/post/post-widgets.styl
source/css/_common/components/third-party/search.styl
source/css/_common/outline/footer/footer.styl
source/css/_common/outline/header/header.styl
source/css/_common/outline/outline.styl
source/css/_common/outline/sidebar/sidebar-nav.styl
source/css/_common/scaffolding/base.styl
source/css/_common/scaffolding/tags/tabs.styl
source/css/_schemes/Gemini/index.styl
source/css/_schemes/Mist/_menu.styl
source/css/_schemes/Mist/index.styl
source/css/_schemes/Muse/_layout.styl
source/css/_schemes/Pisces/_layout.styl
source/css/_schemes/Pisces/_menu.styl
source/js/schemes/muse.js
source/js/schemes/pisces.js
source/js/utils.js

Replace id with class name

---

scripts/events/index.js
scripts/events/lib/config.js

Due to https://github.com/hexojs/hexo/issues/3753 and previous story #970

Replace lodash with native API

---

layout/_partials/sidebar/site-overview.swig

Currently in docs there is a behavior that includes doesn't show author image when is not present. But even not present im YAML an image is rendering.
Author image is showing only there is a author image on YAML.
- Link to demo site with this changes: 
https://www.geresdev.com.br/
In Hexo `next.yml` don't include avatar.url

Make author image optional

---

scripts/events/lib/injects.js

If there is no extension, will add `.swig`.
If there is no extension, will add file's extname or `.swig`.
e.g. use md extname https://gitlab.com/JiangTJ/next-test/blob/master/scripts/fix-scheme.js#L15-17

Set inject default extname from file's extname

---

layout/_third-party/comments/changyan.swig
layout/_third-party/comments/disqus.swig
layout/_third-party/comments/disqusjs.swig
layout/_third-party/comments/gitalk.swig
layout/_third-party/comments/livere.swig
layout/_third-party/comments/valine.swig
scripts/filters/comment/changyan.js
scripts/filters/comment/disqus.js
scripts/filters/comment/disqusjs.js
scripts/filters/comment/livere.js
scripts/filters/comment/valine.js
source/js/utils.js

- Link to demo site with this changes: https://jiangtj.gitlab.io/next-test/gemini/post/hello-world/

Use IntersectionObserver to lazyload comments

---

layout/_scripts/pjax.swig
source/js/motion.js

- Issue resolved:
When animation and pjax are both turned on, the sub-menu icons will become invisible after a pjax reload.
- Reason:
Sub-menu items have opacity of 0, as defined in css together with menu-item, which need to be animated to opacity 1 by velocity. However sub-menu is also in the part that pjax refreshes, and pjax script overlooks them, resulting in invisibility after pjax reload.
- A demo (with Pisces): https://foxb612.github.io/sub-menu-bug.gif
Bug fixed.

Fix conflict between animation of sub-menu icons and pjax

---

scripts/filters/comment/disqus.js
scripts/filters/comment/valine.js

Fix valine & disqus meta for #1305

---

_config.yml
layout/_third-party/comments/gitalk.swig

Gitalk update https://github.com/gitalk/gitalk/pull/344
solve use Gitalk apper 「[GitHub API] Deprecation notice for authentication via URL query parameters」
```yml
gitalk:
enable: true
...
accessToken: # here
...
```

New Gitalk option: accessToken

---

scripts/helpers/next-config.js

Issue resolved: https://github.com/theme-next/hexo-theme-next/issues/1373
There seems to be only `path` in the code. If the local search plugin is not installed, `config.search` does not exist.
```yml
```

Fix config.search.path is null

---

_config.yml
layout/_third-party/math/mathjax.swig
source/css/_common/components/third-party/math.styl

https://docs.mathjax.org/en/latest/upgrading/whats-new-3.0.html

Support MathJax v3.0

---

source/css/_common/components/back-to-top-sidebar.styl
source/css/_schemes/Pisces/_sidebar.styl
source/js/utils.js

Add margin-bottom: 10px to the root div, to make this part more comfortable.
Just a style patch.
- Screenshots with this changes: 
Before adding an extra margin:
Seems like the bottom of the links-of-blogroll is too narrow, may cause a weird feeling.
After applied this change:
- Link to demo site with this changes: 
https://io.backrunner.top
You can see the part on the left.

Style back-to-top button to make sidebar more comfortable

---

source/css/_common/outline/sidebar/sidebar.styl

The back2top button can't apply the shadow, it looks uncomfortable.
I removed the shadow of sidebar when back2top.sidebar is true.

Remove box-shadow of .sidebar when back2top.sidebar is true

---

layout/_macro/post.swig
layout/_partials/header/brand.swig
source/css/_colors.styl
source/css/_common/components/post/post-followme.styl
source/css/_common/outline/header/menu.styl
source/css/_common/outline/header/site-nav.styl
source/css/_mixins.styl
source/css/_schemes/Mist/_menu.styl
source/css/_schemes/Muse/_menu.styl
source/css/_schemes/Pisces/_header.styl
source/css/_schemes/Pisces/_menu.styl
source/js/algolia-search.js
source/js/local-search.js

Optimize the position of search icon on mobile

---

layout/_third-party/math/mathjax.swig

`amsCd.js` and `AMScd.js` cause 404 error
`amsCd.js` and `AMScd.js` redirect to `amscd.js`
N/A

Redirect amscd for mathjax3

---

source/css/_colors.styl
source/css/_common/scaffolding/buttons.styl
source/css/_common/scaffolding/comments.styl
source/css/_schemes/Mist/_posts-expand.styl
source/css/_schemes/Muse/_header.styl
source/css/_variables/Pisces.styl
source/css/_variables/base.styl

In current released version, when dark mode and scheme Pisces or Gemini  is enabled, the button in post-expand is still using the default styles:
I made a set of dark styles for these buttons:
hover:

Fix dark styles of buttons

---

source/js/local-search.js

Escaping html in search results

---

_config.yml
layout/_macro/post-collapse.swig
layout/_macro/post.swig
layout/_partials/header/brand.swig
layout/_partials/header/index.swig
layout/_partials/header/menu.swig
layout/_partials/page/page-header.swig
layout/_partials/search/index.swig
layout/category.swig
layout/tag.swig
source/css/_common/components/post/post-collapse.styl
source/css/_common/components/post/post-header.styl
source/css/_common/components/third-party/search.styl
source/css/_common/outline/header/site-meta.styl
source/css/_variables/base.styl

References:
> Multiple H1 Headings: How to Handle Them for SEO & Accessibility?
> https://www.youtube.com/watch?v=zyqJJXWk0gk
> https://www.youtube.com/watch?v=WsgrSxCmMbM
According to google, multiple h1 on the page will not negatively affect seo.
Tests have shown that if all pages are required to have one and only one h1, then `brand.swig` cannot be cached, which results in an ~8% slowdown in `hexo g`.
https://github.com/theme-next/hexo-theme-next/blob/aee74badd046d7d70b661a8a70110016f62858cb/layout/_partials/header/brand.swig#L22
```
{%- if is_post() or is_page() %}span{% else %}h1{%- endif %}
```

Remove `seo` option in `_config.yml`

---

_config.yml
languages/en.yml
layout/_partials/footer.swig

Stay Simple. Stay NexT.
Revert https://github.com/iissnan/hexo-theme-next/pull/1886
See also https://github.com/iissnan/hexo-theme-next/issues/1873
For developers:
Get Hexo version: `<meta name="generator">` in `<head>`
Get NexT version: `console.log(CONFIG.version)`

Simplify footer.powered settings

---

source/js/algolia-search.js
source/js/bookmark.js
source/js/local-search.js
source/js/next-boot.js
source/js/schemes/muse.js
source/js/schemes/pisces.js

From the [doc](https://developer.mozilla.org/zh-CN/docs/Web/Events/DOMContentLoaded) we know that the target of  event "DOMContentLoaded" should be document not the window. In some cases such as rocket loader of cloudflare, the events bind on the window will never be fired.
```yml
```

Fix: bind event DOMContentLoaded on document insteadof window

---

layout/_partials/footer.swig

The path to `gongan_icon_url` may be incorrect when it is set to a relative path like `gongan.png` in _config.yml.
For example, assume `gongan_icon_url` is `gongan.png` and current page url is `localhost:4000/page/3/`, the exact source of the generated img element is `localhost:4000/page/3/gongan.png`, rather than `localhost:4000/gongan.png`.
It should be wrapped with `url_for` like [this](https://github.com/theme-next/hexo-theme-next/blob/a7a948a08f48dbe48879e277703d75706aec18e5/layout/_partials/sidebar/site-overview.swig#L4).
```yml
footer:
beian:
gongan_icon_url: beian.png
```

Wrap `gongan_icon_url` with `url_for`
