theme-next/hexo-theme-next

- README.md
> add recommend markdown editor

- docs/cn/DATA-FILES.md
- docs/cn/INSTALLATION.md
- docs/cn/README.md
- docs/cn/UPDATE-FROM-5.1.X.md
- languages/zh-Hans.yml
> What are the guidelines on commit message? I can't access the [documentation site](https://theme-next.org) currently.
* `post/totalcount` and `post/totaltime` in `languages/zh-Hans.yml` are not translated.
* Documentations under `docs/cn` are not translated.
* Untranslated words in `zh-Hans` are now translated.
* Translations for documentations, including `DATA-FILES.md`, `INSTALLATION.md` and `README.md`, are finished.
N/A.
> Refine Simplified Chinese Translations and Add Translations for documents in Simplified Chinese.

- layout/_macro/reward.swig
- layout/_macro/wechat-subscriber.swig
> If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'. Then you'll find that  the images of 'reward and wechat-subscriber area' can't display. This upgrade has fixed the bug.
If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'. Then you'll find that the images of 'reward and wechat-subscriber area' can't display. This upgrade has fixed this problem.
> fixed a bug of the reward and the wechat-subscriber template

- _config.yml
[https://github.com/theme-next/hexo-theme-next/pull/5#issuecomment-354814184](https://github.com/theme-next/hexo-theme-next/pull/5#issuecomment-354814184)
> add message for reading_progress

- layout/_partials/head.swig
- layout/_third-party/needsharebutton.swig
> move needmoreshare_css to head

- languages/zh-Hans.yml
> Fix wrong translation in zh-Hans

- layout/_partials/comments.swig
If any other comment system will be used instead of  the already set `changyan` & `valine` system, the `appid` & `appkey` are needed to be deleted or commented.
Issue Number(s): [#1819](https://github.com/iissnan/hexo-theme-next/issues/1819)
To switch comment system more conveniently, the `theme.changyan.enable` and `theme.valine.enable` are added. In this way, the switch of comment system can be done just changing the `enable` from `false` to `true` without regarding `appid` & `appkey`.
```yml
...
```
> Add comment.enable to switch comment conveniently

- _config.yml
- layout/archive.swig
Archive template (`layout/archive.swig`) always shows the "cheers" text at the top. For instance:
> Nice! 77 posts in total. Keep on posting.
Added `cheers_enabled` boolean flag that allows users to toggle the cheers text. Defaults to `true`, so that there are no behavioral changes unless explicitly configured.
```yml
cheers_enabled: true
```
Or...
```yml
cheers_enabled: false
```
> Added cheers_enabled config option

- docs/cn/DATA-FILES.md
Update translation for the DATA-FILES.md changes   (de3eea692b34af82f452c365a75ba4abf7974cb8).
> Update translation for the DATA-FILES.md changes.

- layout/_macro/post.swig
reading_progress appeared in index page
reading_progress only appear in post
> fix reading_progress appear in index

- _config.yml
- layout/_layout.swig
- layout/_third-party/pangu.swig
Comes from theme-next/hexo-theme-next#51
Thanks @sli1989 
Mix Chinese and English content without space if you don't manually add spaces to it.
Add pangu.js, with this js loaded, it will add spaces between Chinese and English words even if you don't manually add them in Markdown file.
```yml
pangu: false
```
> Add pangu support

- languages/ru.yml
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/679/ru/review/498)
> Update RU language.

- languages/ru.yml
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/698/ru/review/503)
> Update RU language [2].

- source/css/_schemes/Mist/index.styl
- source/css/_schemes/Muse/index.styl
At present, the text-align of posts is left in mobile of Muse&Mist scheme,  if you want to justify text-align on mobile, just uncomment `@import "../Pisces/_posts";` in `\source\css\_schemes\Muse\index.styl` or `\source\css\_schemes\Mist\index.styl`.
This PR adds the annotation of text-align on mobile in `\source\css\_schemes\Muse\index.styl` or `\source\css\_schemes\Mist\index.styl`.
<!--
Short description in several words here.
Issue Number(s): #xxxx.
1.	Short description of modified file [1].			xxxxxxx
2.	Short description of modified file [2].			xxxxxxx
3.	Short description of modified file [3].			xxxxxxx
* ADD: `newFunction` in `utils.js`.
* DEL: `oldFunction` from …
> Add annotation of text-align on mobile in Mist&Muse

- _config.yml
- docs/MATH.md
- docs/zh-CN/MATH.md
Add new optionnal cdn for katex, and supplement docs about cdnjs is blocked in some parts of China.
```yml
katex:
cdn: //cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css
#cdn: //cdn.bootcss.com/KaTeX/0.7.1/katex.min.css
#cdn: //cdn.jsdelivr.net/katex/latest/katex.min.css
```
> Add bootcdn for katex and add docs about cdnjs blocked in China

- _config.yml
- layout/_macro/sidebar.swig
- layout/_third-party/github-banner.swig
- source/css/_common/components/sidebar/sidebar-author-links.styl
- source/css/_common/components/sidebar/sidebar.styl
- source/css/_mixins/Pisces.styl
- source/css/_schemes/Pisces/_sidebar.styl
1. Added extlinks on sidebar author links.
2. Fixed unworked `transition` in sidebar author links on Mist & Muse.
> Extlinks additions.

- README.md
- docs/ru/README.md
- docs/zh-CN/README.md
> Update Live Preview link

- _config.yml
> Update creative commons license

- _config.yml
- languages/_en.yml
- languages/zh-CN.yml
- layout/_macro/post.swig
- layout/_third-party/analytics/busuanzi-counter.swig
- layout/_third-party/analytics/firestore.swig
Issue Number(s): #108 
Add hover text for some confusing icon. In the above case , someone maybe be confusing with two date.
Hover text, such as “created” “modified” maybe more favorable in many cases.
**page_pv with title**
**page_pv with hover text.**, need the following config.
```
post_meta:
item_text: false
```
**site_pv with hover text:**
* Link to demo site with this changes: http://xusong.vip/2018/02/09/demo/
```yml
...
```
> add hover text for PV UV  -- optimized

- layout/_partials/breadcrumb.swig
- layout/_partials/page-header.swig
- layout/page.swig
- source/css/_common/components/pages/breadcrumb.styl
- source/css/_common/components/pages/pages.styl
Automatically show «BreadCrumbs» on subpages.
P.S. Feature was maded with assist by Tsanie.
> Added BreadCrumbs feature.

- _config.yml
- bower.json
- package.json
Theme Version 6.0.5 has published, but in the `_config.yml` `bower.json` `package.json` three files, version was `6.0.4` now.
Issue Number(s): #151
Change version number to 6.0.5.
```yml
...
```
> update version number

- source/css/_common/scaffolding/tables.styl
After that, table looks better.
Issue Number(s):  #154 
* Link to demo site with this changes: [table demo](https://blog.eson.org/2018/02/23/network/%E7%BD%91%E7%BB%9C%E5%8D%8F%E8%AE%AE-OSI%E4%B8%83%E5%B1%82%E6%A8%A1%E5%9E%8B/%E7%BD%91%E7%BB%9C%E5%88%86%E5%B1%82/)
<!--
Short description in several words here.
Issue Number(s): #xxxx.
1.	Short description of modified file [1].			xxxxxxx
2.	Short description of modified file [2].			xxxxxxx
3.	Short description of modified file [3].			xxxxxxx
* ADD: `newFunction` in `utils.js`.
* DEL: `oldFunction` from `utils.js`
Live demo [here](http://site.com/).
> remove style  table-layout: fixed;

- README.md
- docs/ru/README.md
- docs/zh-CN/README.md
- layout/_partials/head/head-unique.swig
https://github.com/hexojs/hexo/pull/2535
Since this PR, hexo has already generate meta tag "keywords" for us, so we don't need to do that again
* Link to demo site with this changes: https://raincal.com/
```yml
...
```
> Fix duplicate meta tag keywords

- docs/LEANCLOUD-COUNTER-SECURITY.md
- docs/zh-CN/LEANCLOUD-COUNTER-SECURITY.md
> Shorten leancloud counter security docs

- .github/CONTRIBUTING.md
- docs/zh-CN/CONTRIBUTING.md
Add contributing.md in EN&CN lang.
> Add contributing.md in EN&CN lang

- .github/CODE_OF_CONDUCT.md
- docs/zh-CN/CODE_OF_CONDUCT.md
Add code-of-couduct.md
```yml
...
```
> Add code-of-couduct.md

- .github/CONTRIBUTING.md
- docs/zh-CN/CONTRIBUTING.md
Update guide for creating releases in CONTRIBUTING.MD
> Update guide for creating releases in CONTRIBUTING.MD

- layout/_third-party/copy-code.swig
No visual changes, but more compatible in old browser.
* Link to demo site with this changes: https://blog.maple3142.net/
Don't need to change anything.
> change copy-button position to absolute

- layout/_macro/post.swig
The related issue: #226 
```yml
...
```
> Force scroll_to_more anchor to be #more

- _config.yml
> Add CDN examples for theme-next-three

- layout/index.swig
> Replaced `&mdash;` with `&ndash;` for better visibility.

- scripts/helpers.js
> Fixed NexT `package.json` path on Windows.

- .github/CONTRIBUTING.md
- docs/zh-CN/CONTRIBUTING.md
> Add Labels Rules guideline

- source/js/src/motion.js
TOC displayed in Overview if Overview was selected when open sidebar
1. If you open automatically sidebar with post，TOC display correctly.
2. clicking the overview, and close the sidebar.
3. open the sidebar, the TOC will display in overview.
TOC does not display in Overview if Overview was selected when open sidebar
> Fix TOC displayed in Overview

- scripts/tags/group-pictures.js
Refactor `group-pictures.js` since its [code quality](https://app.codacy.com/app/theme-next/hexo-theme-next/file/21767797035/issues/source) is too low.
Dom is correctly rendered, but its css is broken.(It also broken before this refactoring.)
> Refactor group-pictures

- source/js/src/schemes/pisces.js
> Fixed & Optimized for #426.

- source/js/src/schemes/pisces.js
- source/js/src/utils.js
1. If sidebar taller than content (to prevent bottom jumping).
2. Fixed `resizeListener` function.
3. Fixed init back to top in sidebar.
> Fixed resize filter & affix & back to top for sidebar  (#431).

- source/js/src/utils.js
> Fix for `offset` option. [2]

- _config.yml
Add an option
For many Chinese users, Weibo is one of their main social medias, so I add a new option here so they can link their weibo profile page directly.
```yml
social:
Weibo: http://weibo.com/yourname || weibo
...
```
> Feat: Add sina weibo option to social block in sidebar settings

- _config.yml
> Format code in _config.yml

- _config.yml
- layout/_third-party/pdf.swig
> Format code & change default CDN for pdfobject

- source/css/_schemes/Gemini/index.styl
- source/css/_schemes/Pisces/_layout.styl
- source/css/_schemes/Pisces/_sidebar.styl
- source/js/src/schemes/pisces.js
> Fixed sidebar under Pisces / Gemini schemes for IE 11.

- layout/_macro/sidebar.swig
- layout/_partials/head/head-unique.swig
- layout/_partials/head/head.swig
- layout/_partials/search/swiftype.swig
- layout/_scripts/boostrap.swig
- layout/_scripts/commons.swig
- layout/_scripts/noscript.swig
- layout/_scripts/pages/post-details.swig
- layout/_scripts/schemes/gemini.swig
- layout/_scripts/schemes/pisces.swig
- layout/_scripts/vendors.swig
- layout/_third-party/analytics/application-insights.swig
- layout/_third-party/analytics/baidu-analytics.swig
- layout/_third-party/analytics/tencent-analytics.swig
- layout/_third-party/analytics/vkontakte-api.swig
- layout/_third-party/bookmark.swig
- layout/_third-party/comments/changyan.swig
- layout/_third-party/comments/disqus.swig
- layout/_third-party/comments/gitalk.swig
- layout/_third-party/comments/gitment.swig
- layout/_third-party/comments/livere.swig
- layout/_third-party/comments/valine.swig
- layout/_third-party/exturl.swig
- layout/_third-party/math/mathjax.swig
- layout/_third-party/pangu.swig
- layout/_third-party/pdf.swig
- layout/_third-party/rating.swig
- layout/_third-party/scroll-cookie.swig
- layout/_third-party/search/localsearch.swig
***
***
https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Ftheme-next.org%2Fnext-6-0-6-released%2F
> Fixed W3 validator errors.

- layout/_third-party/comments/disqus.swig
> Fixed Disqus URL. Again. A little bit hard.

- layout/_macro/post.swig
Invalid metadata generation at index.
Metadata generation fixed.
> * Fix for metadata generation at index.

- _config.yml
- layout/_macro/post.swig
- source/css/_common/components/pages/archive.styl
- source/css/_common/components/post/post-reward.styl
Issue Number(s): #181 #333
```yml
...
```
> Fix #181 and #333

- layout/_third-party/search/localsearch.swig
Local search generated the wrong URL and lead to the empty page.
Now local search generated correct URL
```yml
...
```
> Fix localsearch wrong article url

- layout/_third-party/analytics/google-analytics.swig
> Edit Google Analytics reference file address

- source/js/src/algolia-search.js
- source/js/src/scrollspy.js
- source/js/src/utils.js
> Revert using template literals in client side scripts.

- docs/LEANCLOUD-COUNTER-SECURITY.md
This may be a little better for beginners
> add: details of configuration

- source/css/_common/components/post/post-expand.styl
- source/css/_common/components/post/post-gallery.styl
- source/css/_common/components/post/post-meta.styl
Issue resolved #601
```yml
...
```
> Fix #601 Ordered list nested in unordered list became unordered

- source/js/src/utils.js
> Fix #609: Code block css style error

- _config.yml
- layout/_third-party/analytics/google-analytics.swig
Please see issure [here](https://github.com/theme-next/hexo-theme-next/issues/617)
Issue resolved #617 
add localhost filter for google analytics
```yml
google_analytics: 
tracking_id: [put your ga id here]
localhost_ignored: true
```
> FIX #617 add localhost filter for google analytics

- _config.yml
- layout/_third-party/math/mathjax.swig
- layout/_third-party/schedule.swig
- source/js/src/utils.js
> Optimize the displaying of fancybox, mathjax and schedule

- layout/_macro/sidebar.swig
URLs of categories & tags in sidebar contain index.html, it's not cool.
Get rid of index.html and URLs will be categories/ and tags/.
```yml
site_state: true
```
> Fix: URLs of categories & tags in sidebar contain index.html

- layout/_macro/sidebar.swig
- layout/_third-party/analytics/vkontakte-api.swig
- layout/category.swig
- layout/tag.swig
- scripts/tags/button.js
- scripts/tags/full-image.js
- scripts/tags/label.js
- source/css/_common/components/sidebar/sidebar-feed-link.styl
- source/css/_common/components/sidebar/sidebar.styl
- source/css/_common/components/sidebar/site-state.styl
Space between `author_info` and `cc-license` is too big (when `site_status` and `feed` is disabled)
```yml
...
```
> Change the spacing between sidebar elements

- _config.yml
- layout/_macro/post.swig
- layout/_partials/github-banner.swig
- layout/_partials/header/brand.swig
- layout/archive.swig
There are 40 `enable:` and 4 `enabled:` in `_config.yml`. This PR make them look better.
```yml
...
```
> Modify some of the descriptions in _config.yml to make them more uniform

- README.md
1. Removed unnecessary comma after "scratch"
2. Changed "whole repository" to "the entire repository"
3 & 4. Combined two sentences into one.
5. Howbeit to "However".
6. Replaced "Discard" with "Reset". There is no "discard" command.
> Made a few documentational edits

- source/css/_common/components/post/post-meta.styl
- source/css/_schemes/Mist/_header.styl
- source/css/_schemes/Mist/_menu.styl
- source/css/_schemes/Muse/_menu.styl
> Refactored Mist & Muse menu bar using `flex`

- _config.yml
- layout/_partials/head/head.swig
https://github.com/theme-next/hexo-theme-next/commit/05adab81fb1c511a9a624985de44cf039de40497#commitcomment-32815429
> Fixed typo in Baidu.

- README.md
- docs/ru/README.md
- docs/zh-CN/README.md
https://bestpractices.coreinfrastructure.org
> Added CII badge.

- README.md
- docs/ru/README.md
- docs/zh-CN/README.md
Go to this link for see: https://github.com/theme-next/hexo-theme-next/tree/thanks-section
P.S. Need to add translate in `zh-CN`.
> Added «Thanks» section

- .github/CONTRIBUTING.md
- docs/zh-CN/CONTRIBUTING.md
> docs: update CONTRIBUTING.md

- .github/release-drafter.yml
> From now release drafts will maked automatically

- README.md
- docs/ru/README.md
- docs/zh-CN/README.md
From new Bug Reports and Feature Requests will linked direct on issue templates.
> Change Feedback section

- .github/stale.yml
Added new labels and improved comment with link to Code of Conduct file (in future this file will be renamed).
> Change Stale bot labels

- .github/weekly-digest.yml
Digest will posted every week in Sunday. First example can be seen here: #772.
> Install Weekly Digest bot

- .github/lock.yml
More information [here](https://github.com/dessant/lock-threads).
> Install Lock bot

- .github/auto_assign.yml
More information [here](https://github.com/kentaro-m/auto-assign/).
> Install Auto Assign bot

- .github/topissuebot.yml
More information [here](https://github.com/adamzolyak/gh-vote-bot).
> Install Top Issues bot

- .github/eslint-disable-bot.yml
More information [here](https://github.com/koddsson/eslint-disable-probot).
> Install ESLint Diable Watcher bot

- .github/config.yml
There are 3 bots installed from 1 organization:
1. [Welcome bot](https://github.com/behaviorbot/welcome)
2. [Request Info bot](https://github.com/behaviorbot/request-info)
3. [Sentiment bot](https://github.com/behaviorbot/sentiment-bot)
See comments inside file for understanding why they needed.
> Install Welcome, Request Info and Sentiment bots

- .github/topissuebot.yml
> Fix Top Issue Label

- .github/support.yml
More information [here](https://github.com/dessant/support-requests).
> Install Support bot

- .github/lock.yml
> Change lockLabel

- .github/auto_assign.yml
- .github/config.yml
- .github/eslint-disable-bot.yml
- .github/mergeable.yml
- .github/release-drafter.yml
- .github/topissuebot.yml
- .github/weekly-digest.yml
1. Add obligatory labels to PR's for Mergeable bot.
2. Add reviewers for Auto-Assign bot.
3. Add To-Do label for todo bot.
4. Add quick-links on docs in each bot config.
> Improve bots configs

- source/css/_common/components/tags/pdf.styl
Issue resolved: https://github.com/theme-next/theme-next-pdf/issues/2
```yml
...
```
> Bug Fix: PDF won't display in particular situation

- .github/auto_assign.yml
> Reduce reviewers for remove scrolling in PR's

- languages/es.yml
Thank's for **Spanish** translation to [Goojira](https://crowdin.com/profile/Goojira)!
> Spanish translation

- languages/fr.yml
Thank's for **French** translation to @jodumont!
> Improve French translation

- _config.yml
> Fix typo in config comments

- languages/fa.yml
Thank's for **Persian** translation to [Mahdi Hosseini](https://crowdin.com/profile/ghost1372)!
> Persian translation

- layout/_third-party/analytics/facebook-sdk.swig
Update facebook-sdk.swig version:2.10 > 3.3
```yml
...
```
> Upgrade Facebook Graph API to v3.3

- layout/_third-party/quicklink.swig
dist/quicklink.umd.js → quicklink.umd.js
See: https://github.com/theme-next/theme-next-quicklink/commit/335378e4c80a1ceea43de63fa9b2432a728a9e38
```yml
...
```
> Change the internal path of quicklink

- .github/CONTRIBUTING.md
- docs/zh-CN/CONTRIBUTING.md
> Expressions and translations in CONTRIBUTING.md

- _config.yml
I search the keyword "dependencies" to install dependencies in this config file, and I find that I forgot to install rss dependencies because there is no keyword "dependencies" in the description of rss.
So I add the keyword "dependencies" to the description of rss.
> Add detailed description about RSS

- _config.yml
- layout/_partials/head/head.swig
> Correct the outdated version number of FontAwesome

- _config.yml
Fix word spelling of comments.
```yml
...
```
> Fix word spelling

- _config.yml
- layout/_macro/post.swig
- layout/_partials/head/head.swig
- layout/page.swig
- source/css/_common/components/third-party/han.styl
- source/css/_common/components/third-party/third-party.styl
> Remove Han support

- layout/_macro/menu/menu-item.swig
- layout/_partials/search/algolia-search.swig
> Remove unnecessary statements in swig templates

- layout/_third-party/comments/livere.swig
Issue resolved: #919 
On non-post pages, LiveRe's comments will show.
```yml
...
```
> Fix referer used by LiveRe on non-post pages

- layout/_macro/post.swig
- source/css/_common/components/post/post-meta.styl
Issue resolved: #867
```yml
...
```
> Refactoring post-meta-divider

- _config.yml
```diff
-  # Internal version: 1.1
+  # Internal version: 1.2.0
-  # reading_progress: //cdn.jsdelivr.net/gh/theme-next/theme-next-reading-progress@1/reading_progress.min.js
+  # reading_progress: //cdn.jsdelivr.net/gh/theme-next/theme-next-reading-progress@1.2.0/reading_progress.min.js
reading_progress:
```
> Update reading_progress vendor version number

- scripts/filters/default-injects.js
TypeError: Cannot read property 'head' of null
Issue resolved: https://github.com/theme-next/hexo-theme-next/issues/960
fix
```yml
...
```
> Fix TypeError: Cannot read property 'head' of null

- _config.yml
- layout/_third-party/tags/caniuse.swig
- scripts/tags/caniuse.js
Issue resolved: #988
```yml
...
```
> Refactor caniuse

- source/css/_common/components/header/site-nav.styl
- source/css/_schemes/Mist/_menu.styl
- source/css/_schemes/Muse/_layout.styl
- source/css/_schemes/Muse/_menu.styl
- source/css/_schemes/Pisces/_menu.styl
> Refactor Muse menu on mobile

- scripts/injects.js
- scripts/merge-configs.js
- source/js/js.cookie.js
- source/js/local-search.js
- source/js/schemes/muse.js
- source/js/utils.js
https://github.com/theme-next/eslint-config-theme-next
> Obey ESLint rules

- layout/_scripts/vendors.swig
- layout/_third-party/analytics/lean-analytics.swig
- source/js/algolia-search.js
- source/js/local-search.js
- source/js/next-boot.js
- source/js/scrollspy.js
- source/js/utils.js
> Drop IE support

- layout/_macro/post.swig
- layout/_partials/head/head-unique.swig
- layout/_partials/head/head.swig
- layout/_partials/header/brand.swig
- layout/_partials/post/post-related.swig
- layout/_partials/post/reward.swig
- layout/_partials/post/wechat-subscriber.swig
- layout/_partials/sidebar/site-overview.swig
- layout/_third-party/comments/disqusjs.swig
- layout/_third-party/comments/gitalk.swig
- layout/_third-party/math/katex.swig
- layout/_third-party/search/algolia-search.swig
Issue resolved: #1029
```yml
...
```
> Use HTML5 syntax instead of XHTML

- _config.yml
> Update docs in _config.yml

- .github/release-drafter.yml
> Update release-drafter exclude-labels

- scripts/filters/exturl.js
- scripts/filters/lazyload.js
- scripts/hexo-event.js
> Fix bugs caused by `this` and optimize the loading of cheerio

- scripts/events/lib/injects.js
- source/css/main.styl
> Refactor inject style path

- layout/_macro/post-collapse.swig
- layout/archive.swig
- layout/category.swig
- layout/tag.swig
Issue resolved: #112
```yml
...
```
> Show year devision in category or tag page

- _config.yml
- layout/_macro/post.swig
- scripts/filters/excerpt.js
> Refactor auto excerpt

- _config.yml
- layout/_partials/pjax.swig
- layout/_third-party/analytics/firestore.swig
- layout/_third-party/analytics/lean-analytics.swig
- layout/_third-party/comments/disqus.swig
- layout/_third-party/tags/mermaid.swig
- layout/_third-party/tags/pdf.swig
- source/js/algolia-search.js
- source/js/local-search.js
- source/js/next-boot.js
- source/js/schemes/muse.js
- source/js/schemes/pisces.js
- source/js/utils.js
> Use Pure JavaScript instead of jQuery [0]

- layout/_partials/comments.swig
- layout/_partials/pjax.swig
- layout/_third-party/comments/disqus.swig
- layout/_third-party/comments/disqusjs.swig
- layout/_third-party/comments/gitalk.swig
- layout/_third-party/comments/valine.swig
- layout/_third-party/facebook-sdk.swig
- layout/_third-party/math/mathjax.swig
- layout/_third-party/tags/mermaid.swig
- layout/_third-party/tags/pdf.swig
- layout/_third-party/vkontakte-api.swig
- source/js/algolia-search.js
- source/js/local-search.js
- source/js/motion.js
- source/js/next-boot.js
- source/js/post-details.js
- source/js/schemes/muse.js
- source/js/schemes/pisces.js
- source/js/utils.js
> Use arrow function in front-end

- layout/_layout.swig
- layout/_macro/post.swig
- layout/_macro/sidebar.swig
- layout/_partials/footer.swig
- layout/_partials/header/index.swig
- scripts/helpers/next-inject.js
> Add next_inject helper

- source/js/local-search.js
> Use insertAdjacentHTML instead of appendChild

- scripts/filters/comment/changyan.js
- scripts/filters/comment/disqus.js
- scripts/filters/comment/facebook-comments-plugin.js
- scripts/filters/comment/valine.js
> Fix space after comment count

- layout/_partials/pjax.swig
- layout/_partials/search/algolia-search.swig
- layout/_partials/search/index.swig
- layout/_partials/search/localsearch.swig
- source/css/_common/components/third-party/search.styl
- source/js/algolia-search.js
- source/js/local-search.js
- source/js/utils.js
> Fix PJAX refresh bugs when search / fancybox enabled

- source/js/utils.js
> IntersectionObserver about TOC

- layout/_layout.swig
- layout/_scripts/index.swig
- layout/_scripts/pjax.swig
- layout/_scripts/three.swig
- source/js/next-boot.js
- source/js/next-pjax.js
- source/js/schemes/pisces.js
- source/js/utils.js
https://github.blog/2018-09-06-removing-jquery-from-github-frontend/
> Use pure JavaScript instead of jQuery [7]

- layout/_third-party/math/katex.swig
> Fix katex uri

- layout/_partials/pagination.swig
- scripts/helpers/next-url.js
https://github.com/hexojs/hexo/pull/3728
https://github.com/hexojs/hexo/issues/3729
> Fix compatibility issues with hexo-util@1.3.0

- layout/_layout.swig
- layout/_macro/post.swig
- layout/archive.swig
- layout/category.swig
- layout/index.swig
- layout/page.swig
- layout/post.swig
- layout/tag.swig
- source/css/_common/components/post/post-eof.styl
- source/css/_schemes/Gemini/index.styl
- source/css/_schemes/Mist/_posts-expand.styl
> Add lang attribute to article tag when specified in front matter

- layout/_partials/footer.swig
> Point to different website based on the scheme

- layout/_partials/sidebar/site-overview.swig
- source/js/utils.js
> Fix known issues

- _config.yml
- layout/archive.swig
- scripts/filters/post.js
`auto_excerpt` is not a feature that the theme should be responsible for. Please search for and install third-party plug-ins yourself.
> Remove cheers and auto_excerpt

- _config.yml
- layout/_partials/head/head.swig
- layout/_partials/sidebar/site-overview.swig
- layout/_third-party/statistics/lean-analytics.swig
- scripts/events/lib/config.js
- scripts/filters/locals.js
- scripts/tags/group-pictures.js
- source/css/_common/outline/sidebar/sidebar-button.styl
- source/css/_schemes/Pisces/_sidebar.styl
- source/js/local-search.js
https://github.com/hexojs/hexo-theme-unit-test/pull/25
https://github.com/hexojs/hexo-generator-feed/pull/96/files
> Remove rss button

- _config.yml
- languages/de.yml
- languages/en.yml
- languages/es.yml
- languages/fa.yml
- languages/fr.yml
- languages/hu.yml
- languages/id.yml
- languages/it.yml
- languages/ja.yml
- languages/ko.yml
- languages/nl.yml
- languages/pt-BR.yml
- languages/pt.yml
- languages/ru.yml
- languages/tr.yml
- languages/uk.yml
- languages/vi.yml
- languages/zh-CN.yml
- languages/zh-HK.yml
- languages/zh-TW.yml
- layout/_partials/post/post-reward.swig
Issue resolved: #717
```yml
reward:
#wechatpay: /images/wechatpay.png
#alipay: /images/alipay.png
paypal: /images/paypal.png
#bitcoin: /images/bitcoin.png
```
> PayPal now supports pay-by-QRCode, so I added it.

- layout/_partials/head/head.swig
- scripts/helpers/next-config.js
> Add next_config helper

- _config.yml
- layout/_third-party/comments/gitalk.swig
Issue resolved: https://github.com/gitalk/gitalk/issues/343
N/A
> [comments] gitalk.swig: fix syntax bug and remove redundant lines introducing access_token

- _config.yml
Replace the gitalk.css link with the compressed
Just updated the comment
> Updated recommended CDN URL in _config.yml

- source/css/_common/components/post/post.styl
- source/css/_common/scaffolding/base.styl
- source/js/utils.js
Issue resolved #1393 
See also #1076
According to the investigation of several members, this issue is related to the behavior of the mouse driver program and the browser. The bug is reproduced on Edge and Safari 13, while Firefox and Chrome are working as expected.
> Optimize the loading of exturl

- _config.yml
- docs/LEANCLOUD-COUNTER-SECURITY.md
- docs/zh-CN/LEANCLOUD-COUNTER-SECURITY.md
- layout/_third-party/statistics/lean-analytics.swig
- source/css/_common/scaffolding/highlight/highlight.styl
Issue resolved: #1421
```diff
leancloud_visitors:
-  betterPerformance: false
+  # Required for apps from CN region
+  server_url: # <your server url>
```
> New leancloud_visitors option server_url

- source/css/_common/components/third-party/search.styl
- source/css/_common/scaffolding/highlight/highlight.styl
- source/js/algolia-search.js
- source/js/local-search.js
> Animation for search-popup

- scripts/events/index.js
> Optimize version condition

- source/css/_common/scaffolding/tables.styl
Issue resolved: https://github.com/hexojs/hexo/issues/4240
> Fix tables text align

- source/css/_common/components/post/post-reward.styl
> beautufy the reward button

- source/js/utils.js
For example, if user changed title, added a lang selector to title section, the bottom one wont work.
If there are more than one language selectors, they will all work.
```yml
language_switcher: true
```
> Optimize language selector

- source/js/utils.js
Issue resolved: #1537 
pick https://github.com/next-theme/hexo-theme-next/commit/0d2b3af50b3b597fb3d0ecd6a6ffdfbf6b92745b
> fix: Chinese TOC cannot jump

- _config.yml
- layout/_partials/footer.swig
The website `http://www.beian.miit.gov.cn` is not available now.
change beian ICP website from `http://www.beian.miit.gov.cn` to `https://beian.miit.gov.cn`
same as before when enabling `beian` in footer
> Bug Fix: Adopt the domain change of Beian ICP
